### PR TITLE
fix: subscribe button

### PR DESCRIPTION
**Pull request by nafees87n**
#37

### CODE REVIEW

**Review by anistark — CHANGES_REQUESTED** [review]
Please change your space settings and commit again. The changes are not that apparent.

**Comment by nafees87n** [comment]
can you please add the hacktoberfest-accepted label

**Review by anistark — APPROVED** [review]
Looks good.

**Comment by nafees87n** [comment]
> can you please add the hacktoberfest-accepted label

@anistark please add `hacktoberfest-accepted` label to this pr

**Comment by anistark** [comment]
Done. Thanks for the suggestion. :)

**Pull request merged**
